apiVersion: v1
kind: Service
metadata:
  name: dev-bca-pakar-auth-service
  namespace: bca-pakar
  labels:
    app: dev-bca-pakar-auth-service
spec:
  selector:
    app: dev-bca-pakar-auth-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: 8080-http
      
---      

kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: dev-bca-pakar-auth-service
  namespace: bca-pakar
  labels:
    app: dev-bca-pakar-auth-service
spec:
  selector: 
    app: dev-bca-pakar-auth-service
    deploymentconfig: dev-bca-pakar-auth-service
  replicas: 1
  template:
    metadata:
      labels:
        app: dev-bca-pakar-auth-service
        deploymentconfig: dev-bca-pakar-auth-service  
    spec:
      containers:
        - name: authservice
          env: 
          - name: SPRING_PROFILES_ACTIVE
            value: openshift   
          ports: 
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          volumeMounts:
            - name: bca
              mountPath: /var/bca/file
              readOnly: false                
          resources:
            limits:
              cpu: "1"
              memory: 1G
            requests:
              cpu: "0.2"
              memory: 512m
          image: image-registry.openshift-image-registry.svc:5000/bca-pakar/dev-bca-pakar-auth-service:latest              
      volumes:
        - name: bca
          persistentVolumeClaim:
            claimName: bca     
