server:
  port: 8080
spring:
  profiles: openshift
  json:
    file:
      user: '/var/bca/file/user.json'
  dataSource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
