server:
  port: 8080
upload:
  path:
    base: /var/bca/images
    menu: /var/bca/images/menu/
    category: /var/bca/images/structures/
    theme: /var/bca/images/themes/
    article: /var/bca/images/articles/
    user: /var/bca/images/users/
spring:
  rest:
    timeout:
      read: 60000
      connection: 60000
  main:
    banner-mode: "off"
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQL10Dialect
  # Enable multipart uploads
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 2MB
      max-request-size: 10MB
  multipart:
    max-size: 2000000
    file-type: image/png,image/jpeg,image/gif,image/avif,image/apng,image/svg+xml,image/bmp,image/x-icon,image/tiff
  article:
    param-tag: "{}|[]"
    width-article-image: 307
    height-article-image: 425
    file-type: image/png,image/jpeg
    max-size: 700000
  profiles: openshift
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://dev-bca-pakar-oauth2-server-d3wiaccred-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/oauth/token_key # JSON Web Key URI to use to verify the JWT token.
          issuer-uri: http://dev-bca-pakar-oauth2-server-d3wiaccred-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/api/auth/me
        token-info-uri: http://dev-bca-pakar-oauth2-server-d3wiaccred-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/oauth/check_token
        auth-server: http://dev-bca-pakar-oauth2-server-d3wiaccred-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com
        doc-server: http://localhost:8080
        wf-server: http://dev-bca-pakar-wf-server-d3wiaccred-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com
      server:
        url: http://dev-bca-pakar-oauth2-server-d3wiaccred-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com
      clientId: 8C21EBEEB1AA3FBFE05400144FFBD319
      clientSecret: da82edc6dcc1af30
    jwt:
      signingkey: pakar123
  dataSource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://36.89.25.220:5432/pakardb3
    username: pakar3
    password: pakar123
    hikari:
      type: com.zaxxer.hikari.HikariDataSource
      pool-name: pakar-doc-pool
      maximum-pool-size: 20
      max-lifetime: 1800000
      idle-timeout: 30000
      minimum-idle: 5
      connection-timeout: 20000