kind: Service
apiVersion: v1
metadata:
  name: dev-bca-pakar-angular
  labels:
    app: dev-bca-pakar-angular
spec:
  selector:
    app: dev-bca-pakar-angular
  ports:
    - port: 8080
      name: http
  type: NodePort
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: dev-bca-pakar-angular
  labels:
    app: dev-bca-pakar-angular
spec:
  selector:                
    matchLabels:     
      app: dev-bca-pakar-angular
  replicas: 1
  template:
    metadata:
      labels:
        app: dev-bca-pakar-angular
        version: v1
    spec:
      containers:
      - name: dev-bca-pakar-angular
        image: image-registry.openshift-image-registry.svc:5000/bca-pakar/dev-bca-pakar-angular:latest
        ports:
        - containerPort: 8080
      restartPolicy: Always